name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Restore dependencies
      run: msbuild /t:restore

    - name: Build
      run: msbuild /p:Configuration=Release

    - name: Install StyleCop.Analyzers
      run: nuget install StyleCop.Analyzers -Version <desired_version> -OutputDirectory .

    - name: Run StyleCop
      run: msbuild /p:StyleCopEnabled=true /p:TreatWarningsAsErrors=true
