name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Restore dependencies
      run: msbuild /t:restore

    - name: Build
      run: msbuild /p:Configuration=Release

    - name: Install StyleCop
      run: dotnet tool install -g StyleCop.Analyzers

    - name: Run StyleCop
      run: dotnet build /p:StyleCopEnabled=true /p:TreatWarningsAsErrors=true
